#Propiedades de la ventana
ANCHO, ALTO = 800, 400		

#Propiedades del escenario
LIMITE_IZQ, LIMITE_ARR = 30, 40
LIMITE_DER, LIMITE_ABA = ANCHO-LIMITE_IZQ, ALTO-LIMITE_IZQ
ANCHO_ESC, ALTO_ESC = LIMITE_DER-LIMITE_IZQ, LIMITE_ABA-LIMITE_ARR

#Constantes Identidades
IDEN_ENEMIGAS_MAX = None
DISTANCIA_PRED = 300
DISTANCIA_PRED_SOLDADO_ENEMIGO = 200
DISTANCIA_PRED_MAGO_ENEMIGO = DISTANCIA_PRED
PROBABILIDAD_SOLDADO = 2/3
PROBABILIDAD_MAGO =1/20

#Variables para el control del juego.
FPS = 60
FRAME = 1/FPS
TIEMPO = FPS/400
